# -*- coding: utf-8 -*-
"""shobspython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrN7qghncZ7Aa4CN0AuHyapjEwE4m-WS
"""

#for loop

lst = [ "shobha", "agra", "assignment", "uttarpradesh" ]

for items in lst:
  print(items)

#if loop

lst1 =[1,2,3,4,5,6,7,8]

lst1

for item in lst1:
  if item%2==0:
    print(item, "is odd")
  else:
   print(item, "is even")