# -*- coding: utf-8 -*-
"""shobspython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrN7qghncZ7Aa4CN0AuHyapjEwE4m-WS
"""

# Armstrong number between 1-1000.

print("Enter 'x' for exit.")
print("Enter the interval (starting and ending number): ")
start = input()
if start == 'x':
    exit()
else:
    end = input()
    lower = int(start)
    upper = int(end)
    for num in range(lower, upper+1):
        tot = 0
        temp = num
        while temp != 0:
            dig = temp % 10
            tot += dig ** 3
            temp //= 10
        if num == tot:
            print(num)