# -*- coding: utf-8 -*-
"""shobspython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrN7qghncZ7Aa4CN0AuHyapjEwE4m-WS
"""

#list and its function

lst=[1,2,3,4,[1,2,3]]

lst

lst.append('shobs')

lst

lst[4][1]

lst.count("shobs")

lst.insert(6,"type")

lst

lst.reverse()

lst

lst.pop(-4)

lst

lstb=["class",84]

lstb

lst.extend(lstb)

lst

#Dictionary and its default function

dict= { "Name": "shobha", "age":24, "surname": "chahar" }

dict

dict.values()

dict.keys()

dict.clear()

dict

dict.copy()

dict= { "name": "shobha chahar", "Age":24 }

dict.get("name")

dict.pop("Age")

#sets and it's function

st = [ 1,2,2,2,4,4,6,7, "name" ]

st

st.

st.append("january")

st

st1 = ["class"]

st.extend(st1)

st

#tuple and it's function

tup = ( "Engineer", "Shobha", "Science" )

tup

tup.index("Science")

tup.count("shobha")

tup.count("Science")

tup.index("Engineer")