# -*- coding: utf-8 -*-
"""shobspython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrN7qghncZ7Aa4CN0AuHyapjEwE4m-WS
"""
# Problem 1

class bankaccount():
    def __init__(self,S_name, balance):
        self.S_name = S_name 
        self.balance = balance

    def deposit(self, amount):
        self.balance += amount
        return print("total amount: ",self.balance)
    def withdraw(self, amount):
        if amount > self.balance:
            return print("total balance is low")
        else:
            self.balance-= amount
            return print("total balance: ",self.balance)

bank = bankaccount('shobha',30000)
bank.deposit(5000)
bank.withdraw(30000)
bank.deposit(500)
bank.withdraw(6000)


# Problem 2
from math import pi, sqrt

class cone:
    def __init__(self, radius, height):
        self.radius = radius
        self.height = height

    def volume(self):
        print("volume of cone is ", self.height*pi*(self.radius**2)/3)

    def surface_area(self):
        print('Surface area of cone is ', pi*self.radius*(self.radius+sqrt((self.height**2)+(self.radius**2))))

coneA = cone(20, 40)
coneA.volume()
coneA.surface_area()

