# -*- coding: utf-8 -*-
"""shobspython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SrN7qghncZ7Aa4CN0AuHyapjEwE4m-WS
"""
# Problem 1
class BankAccount:
 def __init__(self, forename, balance):
		self.forename = shobha
		my_account = forename
print('my_account')

class BankAccount(object):
    def __init__(self, initial_balance=0):
        self.balance = initial_balance
    def deposit(self, amount):
        self.balance += amount
    def withdraw(self, amount):
        self.balance -= amount
  
my_account = BankAccount(15)
my_account.deposit(5)
print(my_account.balance)


# Problem 2
from math import pi, sqrt

class cone:
    def __init__(self, radius, height):
        self.radius = radius
        self.height = height

    def volume(self):
        print("volume of cone is ", self.height*pi*(self.radius**2)/3)

    def surface_area(self):
        print('Surface area of cone is ', pi*self.radius*(self.radius+sqrt((self.height**2)+(self.radius**2))))

coneA = cone(20, 40)
coneA.volume()
coneA.surface_area()

